FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    sumo sumo-tools sumo-doc \
    x11vnc xvfb websockify novnc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir sumolib traci fastapi uvicorn

WORKDIR /server

COPY middleware/ /server/
COPY sumo_config/ /server/sumo_config/

EXPOSE 8080 5555

CMD ["/server/start.sh"]

